//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BizTalk.T4PipelineComponent.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BizTalk.T4PipelineComponent.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The pipeline context parameter cannot be null..
        /// </summary>
        internal static string ContextIsNullMessage {
            get {
                return ResourceManager.GetString("ContextIsNullMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The inbound message parameter cannot be null..
        /// </summary>
        internal static string InboundMessageIsNullMessage {
            get {
                return ResourceManager.GetString("InboundMessageIsNullMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KeyElementName.
        /// </summary>
        internal static string KeyElementName {
            get {
                return ResourceManager.GetString("KeyElementName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KeyValuePairElementName.
        /// </summary>
        internal static string KeyValuePairElementName {
            get {
                return ResourceManager.GetString("KeyValuePairElementName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The context of the inbound message is null..
        /// </summary>
        internal static string MessageContextIsNullMessage {
            get {
                return ResourceManager.GetString("MessageContextIsNullMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required parameters are undefined.\nKeyValuePairElementName = {0}\nKeyElementName = {1}\nValueElementName = {2}\nTemplateName = {3}\nTemplateLocationElementName = {4}\n.
        /// </summary>
        internal static string PipelineParametersUnspecified {
            get {
                return ResourceManager.GetString("PipelineParametersUnspecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tag name of the element within the housing record that contains the KEY, that will be promoted as a T4 template property..
        /// </summary>
        internal static string PropertyDescriptionKeyElementName {
            get {
                return ResourceManager.GetString("PropertyDescriptionKeyElementName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key Value Pair Element Name.
        /// </summary>
        internal static string PropertyDescriptionKeyValuePairElementName {
            get {
                return ResourceManager.GetString("PropertyDescriptionKeyValuePairElementName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logical connection string of template location..
        /// </summary>
        internal static string PropertyDescriptionTemplateLocationElementName {
            get {
                return ResourceManager.GetString("PropertyDescriptionTemplateLocationElementName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The identifying title of the template..
        /// </summary>
        internal static string PropertyDescriptionTemplateNameElementName {
            get {
                return ResourceManager.GetString("PropertyDescriptionTemplateNameElementName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tag name of the element within the housing record that contains the VALUE, that will be promoted as a T4 template property..
        /// </summary>
        internal static string PropertyDescriptionValueElementName {
            get {
                return ResourceManager.GetString("PropertyDescriptionValueElementName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key/Value Pair Key Element Name.
        /// </summary>
        internal static string PropertyNameKeyElementName {
            get {
                return ResourceManager.GetString("PropertyNameKeyElementName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key/Value Pair Element Name.
        /// </summary>
        internal static string PropertyNameKeyValuePairElementName {
            get {
                return ResourceManager.GetString("PropertyNameKeyValuePairElementName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template Location.
        /// </summary>
        internal static string PropertyNameTemplateLocationElementName {
            get {
                return ResourceManager.GetString("PropertyNameTemplateLocationElementName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template Name.
        /// </summary>
        internal static string PropertyNameTemplateNameElementName {
            get {
                return ResourceManager.GetString("PropertyNameTemplateNameElementName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key/Value Pair Value Element Name.
        /// </summary>
        internal static string PropertyNameValueElementName {
            get {
                return ResourceManager.GetString("PropertyNameValueElementName", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon star {
            get {
                object obj = ResourceManager.GetObject("star", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This component spins up an in memory instance of the T4 templating engine, and washes the inbound stream over it..
        /// </summary>
        internal static string T4TemplaterFilePipelineComponentDescription {
            get {
                return ResourceManager.GetString("T4TemplaterFilePipelineComponentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T4 Pipeline Component.
        /// </summary>
        internal static string T4TemplaterPipelineComponentName {
            get {
                return ResourceManager.GetString("T4TemplaterPipelineComponentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.0.
        /// </summary>
        internal static string T4TemplaterPipelineComponentVersion {
            get {
                return ResourceManager.GetString("T4TemplaterPipelineComponentVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TemplateLocationElementName.
        /// </summary>
        internal static string TemplateLocationElementName {
            get {
                return ResourceManager.GetString("TemplateLocationElementName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempted to parse template location from inbound message, and failed..
        /// </summary>
        internal static string TemplateLocationUnspecified {
            get {
                return ResourceManager.GetString("TemplateLocationUnspecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TemplateNameElementName.
        /// </summary>
        internal static string TemplateNameElementName {
            get {
                return ResourceManager.GetString("TemplateNameElementName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempted to parse template name from inbound message, and failed..
        /// </summary>
        internal static string TemplateNameUnspecified {
            get {
                return ResourceManager.GetString("TemplateNameUnspecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ValueElementName.
        /// </summary>
        internal static string ValueElementName {
            get {
                return ResourceManager.GetString("ValueElementName", resourceCulture);
            }
        }
    }
}
